name: Deploy Node API

on:
  workflow_call:
    inputs:
      company:
        required: true
        type: string
      subscription:
        required: true
        type: string
      functionAppName:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  deploy-node-api:
    name: ${{ inputs.company }}
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##############
      # Setup Node #
      ##############
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #########
      # Build #
      #########
      - name: Build
        working-directory: .
        shell: bash
        run: npm run build

      ######################
      # Prune Function App #
      ######################
      - name: Prune Function App
        working-directory: .
        shell: bash
        run: npm prune --production

      ###############
      # Azure Login #
      ###############
      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      ###############################
      # Set Deployment Subscription #
      ###############################
      - name: Set Deployment Subscription
        shell: bash
        run: az account set --subscription ${{ inputs.subscription }}

      #######################
      # Deploy Function App #
      #######################
      - name: Deploy Function App
        uses: Azure/functions-action@v1
        id: fa
        with:
          respect-funcignore: true
          app-name: ${{ inputs.functionAppName }}
          package: .