name: GitHub Release

on:
  workflow_call:

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  github-release:
    name: ${{ github.ref }}
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ###############
      # Get Version #
      ###############
      - name: Get Version
        shell: bash
        run: |
          pattern="refs/heads/"
          ver="${github_ref/$pattern/}"
          echo $ver
          echo "new_version=$ver" >> $GITHUB_ENV
        env:
          github_ref: ${{ github.ref }}

      #########################
      # Create GitHub Release #
      #########################
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.new_version }}
          release_name: ${{ env.new_version }}
          body_path: RELEASE.md
          draft: false
          prerelease: ${{ contains(env.new_version, 'alpha') || contains(env.new_version, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}