name: Vet Node Code

on:
  workflow_call:

############
# Set Jobs #
############
jobs:
  ##############
  # Define Job #
  ##############
  vet-node-code:
    name: ${{ github.repository }}
    runs-on: ubuntu-latest

    ##############
    # Load Steps #
    ##############
    steps:
      #################
      # Checkout Code #
      #################
      - name: Checkout Code
        uses: actions/checkout@v2

      ##############
      # Setup Node #
      ##############
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      ################
      # Install Deps #
      ################
      - name: Install Deps
        working-directory: .
        shell: bash
        run: npm install

      #############
      # Lint Code #
      #############
      - name: Lint Code
        working-directory: .
        shell: bash
        run: npm run lint

      ################
      # Check Format #
      ################
      - name: Check Format
        working-directory: .
        shell: bash
        run: npm run format:check

      #########
      # Build #
      #########
      - name: Build
        working-directory: .
        shell: bash
        run: npm run build

      #############
      # Run Tests #
      #############
      - name: Run Tests
        working-directory: .
        shell: bash
        run: npm run test:ci